spring.application.name=alpha-hotel

spring.datasource.url=jdbc:postgresql://localhost:5432/alpha_hotelDb
spring.datasource.username=postgres
spring.datasource.password=votre_mot_de_passe_postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=votre_login_smtp_brevo
spring.mail.password=votre_mot_de_passe_smtp_brevo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

server.port=8080

app.jwt.secret=votre_cle_jwt_longue_et_securisee
app.jwt.expiration-ms=86400000
app.mail.from=votre_adresse_expediteur_validee@example.com
app.mail.notification-admin=votre_adresse_admin@example.com
app.scheduler.auto-checkout-cron=0 10 0 * * *
app.scheduler.depart-reminder-cron=0 0 18 * * *
app.scheduler.admin-depart-summary-cron=0 0 7 * * *
